name: abc
version: 1.4.5
license: MIT
author: 
url: 
description: 
topics:
  - dds
  - ipc
conan:
  options: 
    - name: shared
      values:
        - true
        - false
      default: false
  packages:
    - name: fmt
      version: 8.1.1
      options:
        header_only: true
  tools:
    - name: doxygen
      version: 1.9.4
    - name: cppcheck
      version: 2.7.5
pip:
  tools:
    - name: conan
      version: 1.55
    - name: metrixpp
      version: 1.7.1
cmake:
  executables:
    - name: main
      src:
        - src/main.cpp
      link:
        - Hello
  libraries:
    - name: Hello
      src:
        - src/Greeter.cpp
      inc:
        - src/Greeter.hpp
      link:
        - fmt::fmt
